#!/bin/bash
#
#  konjungated The Konjungate Core server.
#
#
# chkconfig: 345 80 20
# description: konjungated
# processname: konjungated
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/konjungated, see below
if [ -f /etc/sysconfig/konjungated ]; then
        . /etc/sysconfig/konjungated
fi

RETVAL=0

prog=konjungated
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/konjungated
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/konjungated}

# konjungated defaults to /usr/bin/konjungated, override with BITCOIND_BIN
konjungated=${BITCOIND_BIN-/usr/bin/konjungated}

# konjungated opts default to -disablewallet, override with BITCOIND_OPTS
konjungated_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $konjungated $konjungated_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
